grid_map_visualization:
  ros__parameters:
    grid_map_topic: /elevation_map
    grid_map_visualizations: [elevation_cloud, upper_bound_cloud, lower_bound_cloud, map_region]
    elevation_cloud:
      type: point_cloud
      params:
        layer: elevation

    upper_bound_cloud:
      type: point_cloud
      params:
        layer: upper_bound

    lower_bound_cloud:
      type: point_cloud
      params:
        layer: lower_bound

    map_region:
      type: map_region
      params:
        color: 16777215
        line_width: 0.003
