grid_map_visualization:
  ros__parameters:
    grid_map_topic: /elevation_map_raw

    grid_map_visualizations: [elevation_cloud]
    elevation_cloud:
      type: point_cloud
      params:
        layer: elevation
